// Generated by tools/build_sprites.py — do not edit by hand.
window.SPRITE_DATA = {
 "idle": {
  "file": "assets/sprites/wanderer-idle.png",
  "frames": 6,
  "fw": 288,
  "fh": 260,
  "ax": 144,
  "ay": 236,
  "fps": 8,
  "info": [
   {
    "w": 163,
    "h": 171,
    "top": 66,
    "bottom": 236
   },
   {
    "w": 148,
    "h": 172,
    "top": 64,
    "bottom": 236
   },
   {
    "w": 167,
    "h": 172,
    "top": 64,
    "bottom": 236
   },
   {
    "w": 163,
    "h": 172,
    "top": 65,
    "bottom": 236
   },
   {
    "w": 159,
    "h": 172,
    "top": 64,
    "bottom": 236
   },
   {
    "w": 155,
    "h": 173,
    "top": 63,
    "bottom": 236
   }
  ]
 },
 "run": {
  "file": "assets/sprites/wanderer-run.png",
  "frames": 12,
  "fw": 288,
  "fh": 260,
  "ax": 144,
  "ay": 236,
  "fps": 24,
  "info": [
   {
    "w": 176,
    "h": 166,
    "top": 71,
    "bottom": 236
   },
   {
    "w": 189,
    "h": 167,
    "top": 70,
    "bottom": 236
   },
   {
    "w": 187,
    "h": 163,
    "top": 73,
    "bottom": 236
   },
   {
    "w": 185,
    "h": 162,
    "top": 74,
    "bottom": 236
   },
   {
    "w": 181,
    "h": 164,
    "top": 72,
    "bottom": 236
   },
   {
    "w": 174,
    "h": 161,
    "top": 76,
    "bottom": 236
   },
   {
    "w": 180,
    "h": 160,
    "top": 76,
    "bottom": 236
   },
   {
    "w": 182,
    "h": 163,
    "top": 73,
    "bottom": 236
   },
   {
    "w": 186,
    "h": 162,
    "top": 74,
    "bottom": 236
   },
   {
    "w": 187,
    "h": 163,
    "top": 73,
    "bottom": 236
   },
   {
    "w": 182,
    "h": 165,
    "top": 72,
    "bottom": 236
   },
   {
    "w": 178,
    "h": 162,
    "top": 74,
    "bottom": 236
   }
  ]
 },
 "sword": {
  "file": "assets/sprites/wanderer-sword.png",
  "frames": 12,
  "fw": 288,
  "fh": 260,
  "ax": 144,
  "ay": 236,
  "fps": 25,
  "info": [
   {
    "w": 182,
    "h": 145,
    "top": 91,
    "bottom": 236
   },
   {
    "w": 172,
    "h": 145,
    "top": 91,
    "bottom": 236
   },
   {
    "w": 165,
    "h": 166,
    "top": 70,
    "bottom": 236
   },
   {
    "w": 156,
    "h": 196,
    "top": 41,
    "bottom": 236
   },
   {
    "w": 154,
    "h": 161,
    "top": 75,
    "bottom": 236
   },
   {
    "w": 200,
    "h": 127,
    "top": 109,
    "bottom": 236
   },
   {
    "w": 196,
    "h": 138,
    "top": 98,
    "bottom": 236
   },
   {
    "w": 237,
    "h": 141,
    "top": 95,
    "bottom": 236
   },
   {
    "w": 165,
    "h": 126,
    "top": 110,
    "bottom": 236
   },
   {
    "w": 157,
    "h": 150,
    "top": 86,
    "bottom": 236
   },
   {
    "w": 198,
    "h": 150,
    "top": 86,
    "bottom": 236
   },
   {
    "w": 186,
    "h": 152,
    "top": 84,
    "bottom": 236
   }
  ]
 },
 "bow": {
  "file": "assets/sprites/wanderer-bow.png",
  "frames": 6,
  "fw": 288,
  "fh": 260,
  "ax": 144,
  "ay": 236,
  "fps": 12,
  "info": [
   {
    "w": 149,
    "h": 171,
    "top": 66,
    "bottom": 236
   },
   {
    "w": 178,
    "h": 175,
    "top": 61,
    "bottom": 236
   },
   {
    "w": 165,
    "h": 173,
    "top": 64,
    "bottom": 236
   },
   {
    "w": 194,
    "h": 177,
    "top": 59,
    "bottom": 236
   },
   {
    "w": 165,
    "h": 173,
    "top": 63,
    "bottom": 236
   },
   {
    "w": 140,
    "h": 160,
    "top": 76,
    "bottom": 236
   }
  ]
 },
 "grenade": {
  "file": "assets/sprites/wanderer-grenade.png",
  "frames": 6,
  "fw": 288,
  "fh": 260,
  "ax": 144,
  "ay": 236,
  "fps": 12.5,
  "info": [
   {
    "w": 153,
    "h": 162,
    "top": 74,
    "bottom": 236
   },
   {
    "w": 161,
    "h": 159,
    "top": 78,
    "bottom": 236
   },
   {
    "w": 155,
    "h": 177,
    "top": 59,
    "bottom": 236
   },
   {
    "w": 174,
    "h": 155,
    "top": 81,
    "bottom": 236
   },
   {
    "w": 180,
    "h": 139,
    "top": 97,
    "bottom": 236
   },
   {
    "w": 147,
    "h": 164,
    "top": 72,
    "bottom": 236
   }
  ]
 },
 "jump": {
  "file": "assets/sprites/wanderer-jump.png",
  "frames": 6,
  "fw": 288,
  "fh": 260,
  "ax": 144,
  "ay": 236,
  "fps": 12,
  "info": [
   {
    "w": 152,
    "h": 109,
    "top": 127,
    "bottom": 236
   },
   {
    "w": 135,
    "h": 171,
    "top": 65,
    "bottom": 236
   },
   {
    "w": 139,
    "h": 170,
    "top": 66,
    "bottom": 236
   },
   {
    "w": 138,
    "h": 163,
    "top": 73,
    "bottom": 236
   },
   {
    "w": 133,
    "h": 157,
    "top": 79,
    "bottom": 236
   },
   {
    "w": 135,
    "h": 162,
    "top": 75,
    "bottom": 236
   }
  ]
 },
 "land": {
  "file": "assets/sprites/wanderer-land.png",
  "frames": 6,
  "fw": 288,
  "fh": 260,
  "ax": 144,
  "ay": 236,
  "fps": 12,
  "info": [
   {
    "w": 130,
    "h": 181,
    "top": 56,
    "bottom": 236
   },
   {
    "w": 136,
    "h": 183,
    "top": 53,
    "bottom": 236
   },
   {
    "w": 150,
    "h": 191,
    "top": 45,
    "bottom": 236
   },
   {
    "w": 154,
    "h": 147,
    "top": 90,
    "bottom": 236
   },
   {
    "w": 138,
    "h": 118,
    "top": 118,
    "bottom": 236
   },
   {
    "w": 168,
    "h": 172,
    "top": 64,
    "bottom": 236
   }
  ]
 }
};
